services:
  vezha-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: vezha-app:latest
    environment:
      NODE_ENV: production
      PORT: 3000
      DB_PATH: /db/vezha.sqlite
      ADMIN_TOKEN: vezha-admin
    volumes:
      - ./db:/db
    ports:
      - "3010:3000"
    restart: unless-stopped
